default_role = "scrum_master"

[roles.scrum_master]
email = "completar"
password = "completar"

[roles.product_owner]
email = "completar"
password = "completar"

[roles.team_member]
email = "completar"
password = "completar"

[roles.quality_assurance]
email = "completar"
password = "completar"
